### ISSUE TITLE
Add TPU support

### ISSUE THREAD

**Issue by vatai** [undertherain/benchmarker#12]
It'd be nice to add TPU support. This issue can be a place to collect information and discuss this.

**Comment by vatai** [comment]
Getting benchmarker to run on colab is surprisingly easy. You prefix cli commands with `!` , use `%cd dir` cd. Something like this
```
!git clone ...
%cd /content/benchmarker
!pip install -r requirements.txt
!python -m benchmarker --framework ...
```
I'm starting to implement this.

**Comment by vatai** [comment]
[This notebook](https://colab.research.google.com/github/GoogleCloudPlatform/training-data-analyst/blob/master/courses/fast-and-lean-data-science/07_Keras_Flowers_TPU_xception_fine_tuned_best.ipynb) seems like a good starting point.

```python
%tensorflow_version 2.x
import tensorflow as tf
print("Tensorflow version " + tf.__version__)

try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except ValueError:
  raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

def create_model():
  pretrained_model = tf.keras.applications.Xception(input_shape=[*IMAGE_SIZE, 3], include_top=False)
  pretrained_model.trainable = True
  model = tf.keras.Sequential([
    pretrained_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(5, activation='softmax')
  ])
  model.compile(
    optimizer='adam',
    loss = 'categorical_crossentropy',
    metrics=['accuracy']
  )
  return model

with tpu_strategy.scope(): # creating the model in the TPUStrategy scope means we will train the model on the TPU
  model = create_model()
model.summary()```

**Comment by vatai** [comment]
I have the feeling the `do_FRAMEWORK.py` files are the place to handle the TPU stuff. But `INeuralNet` just does something like:
```python
module_kernel = import_module("...param[problem][name].param['framework']")
self.net = module_kernel.get_kernel(params, remaining_args)
```
This approach would need to have the framework in the problem directory to handle this, but I'd say that would lead to a lot of redundant code, and there should be a "model creation wrapper" in `do_FRAMEWORK.py` or something like that. (Not sure yet, just thinking for now).

**Comment by vatai** [comment]
@undertherain we can consider this closed, right?

**Comment by undertherain** [comment]
uhm... we'll get local TPUs sooner or later
but let's open a new one then
