### ISSUE TITLE
Duplicated ImageNet(?) data generation code

### ISSUE THREAD

**Issue by vatai** [undertherain/benchmarker#18]
The ImageNet style problems (vgg and resnet for now) need the same code (which is duplicated for now). They should be refactored so they share/reference the same code.

Where should this code be? How about `benchmarker/util/data/imagenet.py` (and then import this in the problems `data.py` file)

**Comment by undertherain** [comment]
Yep, can place there
even something like bencmarker/data/synthetic/imagenet 
potentially there will be more datasets, real and synthetic, so mayble let's not keep em inside `utils`
also current `utils/data` seem to contain some legacy junk

**Comment by undertherain** [comment]
and move `benchmarker.modules.problems.images_randomized` there as well

**Comment by vatai** [comment]
When you say
> so mayble let's not keep em inside `utils`
Maybe `./benchmarker/data/`

So it would look like
```
.
├── benchmarker
│   ├── modules
│   │   ├── blas
│   │    ....
│   │   ├── problems
│   │   │   ├── alltoall
│   │   │   ├── ...
│   ├── util
│   ├── data
│   └── vis
├── logs
└── test
```
