### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by vatai** [undertherain/benchmarker#19]
Write tests so CI tells us when we break something :)

Basically there should be a test for (approximately) every framework * every model (there will be some exceptions of course). Not sure about different parameters...

**Comment by vatai** [comment]
Shouldn't we have a table to maintain something like what model/problem is available for what framework?

Maybe auto generated.

Maybe in relation to #11?

**Comment by undertherain** [comment]
for tests simple objective is to cover all lines of code, which is easily checkable by `coverage` and reported nicely by services like codecov or coverity - which we should do 
covering all possible options - well, should be mostly covered by that, but of course can add extra

**Comment by vatai** [comment]
Ok, so if tests result in 100% code coverage... this issue can be considered closed?!

**Comment by undertherain** [comment]
yeah why not
not many projects boast 100% coverage)

**Comment by vatai** [comment]
I'm figuring out how to write the tests.
In `benchmarker/__main__.py` calls `.benchmarker.run` with `args` and `unknown_args` (returned by `parser.parser_known_args()`.

So, in the test, should I also be 
- calling `.benchmarker.run()` with the appropriate parameters, or
- is there a better nicer way to do this, maybe this https://stackoverflow.com/questions/18668947/how-do-i-set-sys-argv-so-i-can-unit-test-it
- or is this unittesting and the tests should be "smaller"?  (Probably not, I think we need "full" executions, right?)

**Comment by undertherain** [comment]
I usually do something like
https://github.com/vecto-ai/vecto/blob/master/tests/test_cli_misc.py
