### ISSUE TITLE
if GPU requested but not available, TF silently runs on CPU

### ISSUE THREAD

**Issue by undertherain** [undertherain/benchmarker#32]

**Comment by vatai** [comment]
If I request a GPU but there are no GPUs, then it fails. Right?

But when I request --gpus=101 (while only --gpus=0 exists), it seems it still runs on --gpus=0 (not the CPU).

**Comment by undertherain** [comment]
it first of all not always fails - and that's something to fix
2 - yeah in some parts it ignores specified GPU id ><

**Comment by vatai** [comment]
It is wrong, I agree. But I couldn't make it "silently run on CPU" :confused:

**Comment by undertherain** [comment]
for some frameworks, likely tF

**Comment by vatai** [comment]
Was this on the/after merging TPU branch, or before?

I think this can be easily solved with the `get_kernel()` method. It maybe even good for multi-gpu too. See the `get_strategy()` method in `do_tensorflow.py`
