### ISSUE TITLE
Add Cosmoflow

### ISSUE THREAD

**Issue by vatai** [undertherain/benchmarker#70]
From MLPerf HPC

**Comment by undertherain** [comment]
the model is as dumb as it gets

https://github.com/sparticlesteve/cosmoflow-benchmark/blob/master/models/cosmoflow_v1.py

**Comment by vatai** [comment]
Ok. Will do in there afternoon.

**Comment by vatai** [comment]
After some very sophisticated backtracking with ctrl+f and githubs search functionality I found that it reads this yml file: https://github.com/sparticlesteve/cosmoflow-benchmark/blob/master/configs/cosmo.yaml 

And I guess the relevant data is:
```
    input_shape: [128, 128, 128, 4]
    target_size: 4
```
the input and output size, i.e. shape of the data which needs to be generated.
