### ISSUE TITLE
Runtime error with conv1d when backend=DNNL

### ISSUE THREAD

**Issue by shwetasalaria** [undertherain/benchmarker#91]
Running conv1d with backend=DNNL gives error as "RuntimeError: opaque tensors do not have strides" but works fine with backend=native

Try this:
```python3 -m benchmarker --framework=pytorch --mode=inference --batch_size=32 --problem=conv1d --problem_size=128,3,224 --cnt_filters=64 --size_kernel=7 --dilation=1 --stride=2 --padding=0  --backend=DNNL```

**Comment by vatai** [comment]
I don't get any error on my home computer. I have `intel-mkl 2020.2.254-1` installed. You get this error on Kiev?

**Comment by shwetasalaria** [comment]
Yeah on Kiev, re-checked.

**Comment by vatai** [comment]
If you manage to spack `py-torch@1.6.0`, it works! Close?
